# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - styleprops
  - preview
  - media
  - link
  - unlink
  - image
plugins:
  - table
  - fullscreen
  - preview
  - media
  - link
  - image
apply_source_formatting : true
theme_advanced_more_colors : true
